bl-welcome: s/bl-include.cfg/bl-includes/

diff --git a/bl-welcome b/bl-welcome
--- a/bl-welcome
+++ b/bl-welcome
@@ -39,8 +39,8 @@ TEXTDOMAIN=bl-welcome
 BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
 BL_WELCOME_LIBDIR='/usr/lib/bunsen/welcome'
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$BL_COMMON_LIBDIR/bl-includes" 2> /dev/null; then
+    echo $"Error: Failed to source bl-includes in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
